### PR TITLE
Prepare for Python Packaging

### PR DESCRIPTION
**Pull request by vsoch**
Here is some starting tweaks to get ready for pypi! I've [written up a proper post](https://researchapps.github.io/reproducibility/2016/11/12/python-packages/) with full details about some of the changes, and we can also chat on here :) Here are a few suggestions for moving forward:

- first make an account on pypi. I've already created and uploaded the package info, so I just need to make you the manager of it.
- write tests for your code, and hook up to travis or circle. I can help with this if you need it. The basic idea is that all production version (the ones released on pypi) should have passed tests.
- add a few examples for the different use cases
- consider creating docs with sphinx/read the docs, or just add more to the README.
- consider creating a doi (on zenodo) if you want others to have something to reference.

More details are in the post linked above. Let me know if you have questions, and the account name/email you made for pypi when you get the chanceI hope this is helpful! You've done great work on this code base, and it will be great to have an official package for it :)

### CODE REVIEW

**Comment by RuiShu** [comment]
Thanks! I want to mention that Kaos will remain a strictly Keras/Theano library. The Tensorflow version will be a fresh re-write to leverage Tensorflow's greater flexibility compared to Keras and I intend to house it in a separate repo :)

**Comment by vsoch** [comment]
haha, ok great! I can go ahead and delete the pypi package that I made (unless you want to hold the name for another future package?), and you can create a different package for the current. Kaos is a cool name! I'll change the names back to the right ones on this PR, give me one sec!

**Comment by RuiShu** [comment]
It makes sense to hold onto TensorBayes for the Tensorflow package :P

**Comment by vsoch** [comment]
ok, I'll hold onto it! Check out the scripts.py - you can adapt that into a command line util that will be installed in the user's bin so they can type like:

```
kaos --run awesomemodel... etc.
```

**Comment by RuiShu** [comment]
I can't imagine a use-case for the the aforementioned command line util yet. But I'll keep it around in case I come up with one!

**Pull request merged**
